//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HadiSahiplen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_District
    {
        public int DistrictID { get; set; }
        public short CityID { get; set; }
        public string District { get; set; }
    }
}
